name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Release
        run: |
          mvn release:prepare
          mvn release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}