name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
        dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Configure Git user
        run: |
          git config --global user.name "Rambabu"
          git config --global user.email "rajsofdev@gmail.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Release
        run: |
          mvn release:prepare
          mvn release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        