name: Build and deploy

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: versioning
        run: echo "pringint normal message"
    #   - name: Build and deploy
    #     run: |
    #       # Your build and deployment commands here