name: Semantic Versioning

on:
    push:
        branches: 
            develop
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get commit details
        id: commit_info
        run: |
          COMMIT_ID=$(git rev-parse --short=8 HEAD)
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          COMMIT_DATE=$(git log -1 --date=format:'%Y-%m-%d' --pretty=format:'%cd')
          echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_ENV
  
      - name: Update README.md
        run: |
          sed -i "/^Last Commit:/c\Last Commit: ${COMMIT_ID} - ${COMMIT_MESSAGE} (${COMMIT_DATE})" VERSION_README.md
  
      - name: Commit changes
        run: |
          git config --local user.email "rajsofdev@gmail.com"
          git config --local user.name "Rambabu"
          git add VERSION_README.md
          git commit -m "Update README with last commit details"
          git push origin HEAD:${{ github.ref }}
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}