name: Build and deploy

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install gitversion
        run: |
          curl -sL https://github.com/GitTools/GitVersion/releases/download/5.6.0/gitversion-5.6.0-linux-x64.tar.gz | tar xzf -
          sudo mv gitversion-5.6.0-linux-x64/gitversion /usr/local/bin/
        env:
          GITVERSION_VERSION: 5.6.0

      - name: Generate version
        run: |
          gitversion --mode continuousdelivery --output json > version.json
        env:
          GITVERSION_CONFIG: continuousdelivery

      - name: Replace version placeholder
        run: |
          sed -i 's/@gitversioninformationalversion@/$(cat version.json | jq -r '.informationalVersion')/g' application.properties
        env:
          VERSION_FILE: version.json

      - name: Build and deploy
        run: |
          # Your build and deployment commands here